# Generated by Django 5.2.14 on 2026-05-31 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='vendors.vendor'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['vendor'], name='drivers_dri_vendor__ca578c_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_active'], name='drivers_dri_is_acti_7c5f39_idx'),
        ),
    ]
