# Generated by Django 5.2.14 on 2026-05-31 21:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_vendors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_memberships', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='vendors.vendor')),
            ],
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['type'], name='vendors_ven_type_3f5770_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['owner_user'], name='vendors_ven_owner_u_b2ec53_idx'),
        ),
        migrations.AddIndex(
            model_name='vendormember',
            index=models.Index(fields=['vendor'], name='vendors_ven_vendor__d6894b_idx'),
        ),
        migrations.AddIndex(
            model_name='vendormember',
            index=models.Index(fields=['user'], name='vendors_ven_user_id_4764d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='vendormember',
            constraint=models.UniqueConstraint(fields=('vendor', 'user'), name='uniq_vendor_member'),
        ),
    ]
